### ISSUE TITLE
Copy & Pasting in editing is broken

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/vs-code-bpmn-io#59]
It's currently not possible to copy and paste in the editing feature. Instead, an error is shown in the application console:

```bash
[Embedded Page] ReferenceError: parent is not defined
    at vscode-resource:/Users/niklas.kiefer/pet-projects/vs-code-bpmn-js-extension/node_modules/bpmn-js/dist/bpmn-modeler.development.js:32935:16
    at forEach (vscode-resource:/Users/niklas.kiefer/pet-projects/vs-code-bpmn-js-extension/node_modules/bpmn-js/dist/bpmn-modeler.development.js:358:17)
    at ModdleCopy.copyElement (vscode-resource:/Users/niklas.kiefer/pet-projects/vs-code-bpmn-js-extension/node_modules/bpmn-js/dist/bpmn-modeler.development.js:32925:4)
    at vscode-resource:/Users/niklas.kiefer/pet-projects/vs-code-bpmn-js-extension/node_modules/bpmn-js/dist/bpmn-modeler.development.js:32750:45
    at invokeFunction (vscode-resource:/Users/niklas.kiefer/pet-projects/vs-code-bpmn-js-extension/node_modules/bpmn-js/dist/bpmn-modeler.development.js:5393:14)
    at EventBus._invokeListener (vscode-resource:/Users/niklas.kiefer/pet-projects/vs-code-bpmn-js-extension/node_modules/bpmn-js/dist/bpmn-modeler.development.js:5244:20)
    at EventBus._invokeListeners (vscode-resource:/Users/niklas.kiefer/pet-projects/vs-code-bpmn-js-extension/node_modules/bpmn-js/dist/bpmn-modeler.development.js:5229:25)
    at EventBus.fire (vscode-resource:/Users/niklas.kiefer/pet-projects/vs-code-bpmn-js-extension/node_modules/bpmn-js/dist/bpmn-modeler.development.js:5190:25)
    at vscode-resource:/Users/niklas.kiefer/pet-projects/vs-code-bpmn-js-extension/node_modules/bpmn-js/dist/bpmn-modeler.development.js:32314:17
    at forEach (vscode-resource:/Users/niklas.kiefer/pet-projects/vs-code-bpmn-js-extension/node_modules/bpmn-js/dist/bpmn-modeler.development.js:358:17)
webviewElement.ts:241 [Embedded Page] unhandled error in event listener
webviewElement.ts:241 [Embedded Page] ReferenceError: parent is not defined
    at vscode-resource:/Users/niklas.kiefer/pet-projects/vs-code-bpmn-js-extension/node_modules/bpmn-js/dist/bpmn-modeler.development.js:32935:16
    at forEach (vscode-resource:/Users/niklas.kiefer/pet-projects/vs-code-bpmn-js-extension/node_modules/bpmn-js/dist/bpmn-modeler.development.js:358:17)
    at ModdleCopy.copyElement (vscode-resource:/Users/niklas.kiefer/pet-projects/vs-code-bpmn-js-extension/node_modules/bpmn-js/dist/bpmn-modeler.development.js:32925:4)
    at vscode-resource:/Users/niklas.kiefer/pet-projects/vs-code-bpmn-js-extension/node_modules/bpmn-js/dist/bpmn-modeler.development.js:32750:45
    at invokeFunction (vscode-resource:/Users/niklas.kiefer/pet-projects/vs-code-bpmn-js-extension/node_modules/bpmn-js/dist/bpmn-modeler.development.js:5393:14)
    at EventBus._invokeListener (vscode-resource:/Users/niklas.kiefer/pet-projects/vs-code-bpmn-js-extension/node_modules/bpmn-js/dist/bpmn-modeler.development.js:5244:20)
    at EventBus._invokeListeners (vscode-resource:/Users/niklas.kiefer/pet-projects/vs-code-bpmn-js-extension/node_modules/bpmn-js/dist/bpmn-modeler.development.js:5229:25)
    at EventBus.fire (vscode-resource:/Users/niklas.kiefer/pet-projects/vs-code-bpmn-js-extension/node_modules/bpmn-js/dist/bpmn-modeler.development.js:5190:25)
    at vscode-resource:/Users/niklas.kiefer/pet-projects/vs-code-bpmn-js-extension/node_modules/bpmn-js/dist/bpmn-modeler.development.js:32314:17
    at forEach (vscode-resource:/Users/niklas.kiefer/pet-projects/vs-code-bpmn-js-extension/node_modules/bpmn-js/dist/bpmn-modeler.development.js:358:17)
```

**Comment by pinussilvestrus** [comment]
This got fixed by b8595af46fe5d1566f12fe3a48f860938c0a330a

@nikku 🎉
