### ISSUE TITLE
Running the contributed command: 'extension.bpmn-io.edit' failed.

### ISSUE THREAD

**Issue by programmiererei** [bpmn-io/vs-code-bpmn-io#82]
__Describe the Bug__

Open the BPMN Modeler shows error "Running the contributed command: 'extension.bpmn-io.edit' failed." for existing .bpmn-files. The modeler ist not loaded.

__Steps to Reproduce__

1. development installation:
$ git clone https://github.com/bpmn-io/vs-code-bpmn-io.git
$ cd ./vs-code-bpmn-io
$ npm install
$ code .

2. set breakpoint at

editingProvider.ts, function provideTextDocumentContent

3. debug with F5

4. load file C:\Users\ralfa\Source\repos\his-docu\test.bpmn (I tried with several files. Empty, filled, UTF-8, UTF-16, ANSI,..., all the same).

5. select icon "Open BPMN Modeler" in editor bar or use Strg-Shift-V

Code throws exception at line 
    const contents = fs.readFileSync(docPath, { encoding: 'utf8' });

The call to fs.readFileSync fails for docPath: \\\c:\Users\ralfa\Source\repos\his-docu\test.bpmn

The exception leads to the catch clause in _executeContributedCommand

__Expected Behavior__

Should open modeler.

__Environment__

vs-code-bpmn-io-Version is 0.8.0, vs-code has german language loaded.

Version: 1.46.1 (system setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Datum: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
Betriebssystem: Windows_NT x64 10.0.18363 (german edition)

**Comment by pinussilvestrus** [comment]
Thanks for sharing. Unfortunately, I was not able to reproduce it.

![Kapture 2020-07-07 at 16 46 31](https://user-images.githubusercontent.com/9433996/86798749-6f568500-c071-11ea-888a-a50dbee3ef16.gif)

Are you able to share the exception stack trace and the bpmn file you're using?

**Comment by programmiererei** [comment]
The bpmn file could be emtpy or one of the samples: same error.

"Error: ENOENT: no such file or directory, open '\\c:\Users\ralfa\Source\repos\his-docu\diagram.bpmn'	
at Object.openSync (fs.js:447:3)	
at Object.func (electron/js2c/asar.js:140:31)	
at Object.func [as openSync] (electron/js2c/asar.js:140:31)	
at Object.readFileSync (fs.js:349:35)	
at Object.<anonymous> (electron/js2c/asar.js:542:40)	
at Object.readFileSync (electron/js2c/asar.js:542:40)	
at EditingProvider.provideTextDocumentContent (c:Users\ralfa\Source\repos\vs-code-bpmn-io\out\features\editing\editingProvider.js:18:29)	
at createPanel (c:Users\ralfa\Source\repos\vs-code-bpmn-io\out\extension.js:27:35)	
at c:Users\ralfa\Source\repos\vs-code-bpmn-io\out\extension.js:100:31	
at e._executeContributedCommand (c:Program FilesMicrosoft VS Code
esourcesappoutsworkbenchservicesextensions
odeextensionHostProcess.js:639:863)	
at e.$executeContributedCommand (c:Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:640:217)	
at e._doInvokeHandler (c:Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:804:1013)	
at e._invokeHandler (c:Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:804:705)	
at e._receiveRequest (c:Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:803:344)	
at e._receiveOneMessage (c:Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:802:156)	
at c:Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:800:416	
at e.fire (c:Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:242)	
at v.fire (c:Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:239:274)	
at c:Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:975:649	
at e.fire (c:Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:242)	
at v.fire (c:Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:239:274)	
at Object._receiveMessage (c:Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:243:629)	
at c:Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:240:824	
at e.fire (c:Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:242)	
at p.acceptChunk (c:Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:236:737)	
at c:Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:236:89	
at Socket.t (c:Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:245:185)	
at Socket.emit (events.js:203:13)	
at addChunk (_stream_readable.js:295:12)	
at readableAddChunk (_stream_readable.js:276:11)	
at Socket.push (_stream_readable.js:210:10)	
at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)"

![image](https://user-images.githubusercontent.com/34723518/86807891-949bc100-c07a-11ea-819a-46b2cd22666a.png)

**Comment by programmiererei** [comment]
The double backslashs are missing after pasting the log!

**Comment by programmiererei** [comment]
![image](https://user-images.githubusercontent.com/34723518/86808442-29062380-c07b-11ea-8348-acd0de32e2eb.png)

**Comment by pinussilvestrus** [comment]
All right, I was able to reproduce this on my Windows machine (only). Seems like something is wrong with the created doc path. I'll have a look at it, thanks!

**Comment by programmiererei** [comment]
Oh Windows… Btw, the command „npm run test“ described in „development setup“ doesn´t run in Windows because of „rm“ and „cp“-commands.

 

 

Grüße

 

Ralf Albrecht

 

 

programmiererei nicol gmbh

rotlintstr. 14  …  60316 frankfurt

fon 069.437152  …  fax 069.94414224

 <mailto:albrecht@programmiererei.de> albrecht@programmiererei.de

…

sitz der gmbh:  frankfurt hrb 51334

geschäftsführer: ralf albrecht

 

Von: Niklas Kiefer <notifications@github.com> 
Gesendet: Mittwoch, 8. Juli 2020 08:03
An: bpmn-io/vs-code-bpmn-io <vs-code-bpmn-io@noreply.github.com>
Cc: programmiererei <programmiererei@web.de>; Author <author@noreply.github.com>
Betreff: Re: [bpmn-io/vs-code-bpmn-io] Running the contributed command: 'extension.bpmn-io.edit' failed. (#82)

 

All right, I was able to reproduce this on my Windows machine (only). Seems like something is wrong with the created doc path. I'll have a look at it, thanks!

**Comment by pinussilvestrus** [comment]
>  Btw, the command „npm run test“ described in „development setup“ doesn´t run in Windows because of „rm“ and „cp“-commands

Which terminal are you using?

**Comment by programmiererei** [comment]
Grüße

 

Ralf Albrecht

 

 

programmiererei nicol gmbh

rotlintstr. 14  …  60316 frankfurt

fon 069.437152  …  fax 069.94414224

 <mailto:albrecht@programmiererei.de> albrecht@programmiererei.de

…

sitz der gmbh:  frankfurt hrb 51334

geschäftsführer: ralf albrecht

 

Von: Niklas Kiefer <notifications@github.com> 
Gesendet: Mittwoch, 8. Juli 2020 10:39
An: bpmn-io/vs-code-bpmn-io <vs-code-bpmn-io@noreply.github.com>
Cc: programmiererei <programmiererei@web.de>; Author <author@noreply.github.com>
Betreff: Re: [bpmn-io/vs-code-bpmn-io] Running the contributed command: 'extension.bpmn-io.edit' failed. (#82)

 

Btw, the command „npm run test“ described in „development setup“ doesn´t run in Windows because of „rm“ and „cp“-commands

Which terminal are you using?

**Comment by pinussilvestrus** [comment]
@programmiererei https://github.com/bpmn-io/vs-code-bpmn-io/commit/caaff627f1b096b43d5f8b7026da082a765dc9ad should ship a fix on it on the current `master`. Thanks for your help!
